name: Problem report
description: Please report your problem here to help us improve

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the problem is. You can add screenshots and provide links to help explain it.
      placeholder: Tell us what you see! If you had a compatibility issue, you may want to include a download link to the incompatible software.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: To Reproduce
      description: If applicable, write the exact steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expect to see!
    validations:
      required: true
  - type: input
    id: windows-version
    attributes:
      label: What is your Windows edition and version?
      placeholder: "e.g. Windows 10 Pro 20H2 64-bit"
    validations:
      required: true
  - type: input
    id: sandboxie-version
    attributes:
      label: What version of Sandboxie are you running?
      placeholder: e.g. Sandboxie Plus 1.0.8 64-bit
    validations:
      required: true
  - type: input
    id: security-software
    attributes:
      label: Please mention any installed security software
      description: Even if the real-time protection is disabled, any security solution could still conflict with Sandboxie.
      placeholder: e.g. Windows Defender
    validations:
      required: true
  - type: input
    id: browsers
    attributes:
      label: List of involved browsers
      description: If applicable, in which sandboxed browsers are you seeing the problem?
      placeholder: e.g. Firefox 96.0.2 64-bit
  - type: input
    id: regression
    attributes:
      label: Is it a regression?
      description: If applicable, specify in which Sandboxie version this bug got introduced the first time.
      placeholder: e.g. 5.55.8 64-bit
  - type: textarea
    id: logs
    attributes:
      label: Trace log output
      description: Please consider to take a log and make it available here for analysis. For instructions, see https://git.io/Jwj2y
      placeholder: If you have an actual memory dump, please attach it here in a compressed archive and NOT as simple text output, which often turns out to be insufficient for a proper analysis!
      render: shell
  - type: textarea
    id: sandboxie-config
    attributes:
      label: Sandboxie.ini configuration
      description: If applicable, consider to attach your Sandboxie.ini settings (usually located on C:\Windows or in your installation folder).
      placeholder: |
        [GlobalSettings]
        .....
        
        [UserSettings_xxxxxxxx]
        .....
        
        [DefaultBox]
        .....
        
      render: shell
